// Generated by CoffeeScript 1.6.3
var BSNode;

BSNode = (function() {
  BSNode.prototype.value = null;

  BSNode.prototype.left = null;

  BSNode.prototype.right = null;

  function BSNode(value) {
    this.value = value;
  }

  BSNode.prototype._getChildNumbers = function() {
    if (this.left && this.right) {
      return 2;
    }
    if (this.left === null && this.right === null) {
      return 0;
    } else {
      return 1;
    }
  };

  return BSNode;

})();

module.exports = BSNode;
