// Generated by CoffeeScript 1.6.3
/*
BSTree API
  - clear:boolean (void)
  - isEmpty:boolean (void)

  - add:boolean (value (integer|array of integer))
  - find:BSNode (value (integer))
  - remove:boolean (value (integer))
  - contains:boolean (value (integer))
  - min:value|boolean (void)
  - max:value|boolean (void)
  - print:void (void)
  - toString:void
*/

var BSTree;

BSTree = (function() {
  var _root;

  function BSTree() {}

  _root = null;

  BSTree.prototype.clear = function() {
    return this._root = null;
  };

  BSTree.prototype.isEmpty = function() {
    return _root === null;
  };

  BSTree.prototype.add = function(value) {
    return console.log(value);
  };

  return BSTree;

})();

module.exports = BSTree;
