// Generated by CoffeeScript 1.6.3
var LLNode, LinkedList;

LLNode = require('./LLNode');

/*
  LinkedList Interface
    add(item, index)
    toArray()

    clear()
    contains(item, equalsFunction)
    elementAtIndex(index)
    equals(other, equalsFunction)
    first()
    forEach(callback)
    indexOf(item, equalsFunction)
    isEmpty()
    last()
    remove(item, equalsFunction)
    removeElementAtIndex(index)
    reverse()
    size()
*/


LinkedList = (function() {
  function LinkedList() {}

  LinkedList.prototype.head = null;

  LinkedList.prototype.isEmpty = function() {
    return this.head === null;
  };

  LinkedList.prototype._addToTail = function(value) {
    var current;
    current = this.head;
    while (current.next !== null) {
      current = current.next;
    }
    current.next = new LLNode(value);
    return true;
  };

  LinkedList.prototype._addToIndex = function(value, index) {
    var current, k, new_node, tmp;
    new_node = new LLNode(value);
    current = this.head;
    tmp = current;
    k = 0;
    while (current) {
      current = current.next;
      if (k++ === index - 1) {
        break;
      }
      tmp = tmp.next;
    }
    if (index > k) {
      return false;
    }
    tmp.next = new_node;
    new_node.next = current;
    return true;
  };

  LinkedList.prototype._addToHead = function(value) {
    var new_node;
    new_node = new LLNode(value);
    new_node.next = this.head;
    this.head = new_node;
    return true;
  };

  LinkedList.prototype.add = function(value, index) {
    var new_node;
    if (index == null) {
      index = null;
    }
    new_node = new LLNode(value);
    if (this.isEmpty()) {
      if (index > 0) {
        return false;
      } else {
        this._addToHead(value);
        return true;
      }
    }
    if (index === 0) {
      return this._addToHead(value);
    } else if (index === null) {
      return this._addToTail(value);
    } else {
      return this._addToIndex(value, index);
    }
  };

  LinkedList.prototype.toArray = function() {
    var current, node_array;
    node_array = [];
    current = this.head;
    while (current !== null) {
      node_array.push(current.value);
      current = current.next;
    }
    return node_array;
  };

  return LinkedList;

})();

module.exports = LinkedList;
