// Generated by CoffeeScript 1.6.3
var LLNode;

LLNode = (function() {
  LLNode.prototype.value = null;

  LLNode.prototype.next = null;

  LLNode.prototype.prev = null;

  function LLNode(value) {
    this.value = value;
  }

  return LLNode;

})();

module.exports = LLNode;
