// Generated by CoffeeScript 1.6.3
var BSTree, tree, value, _i, _len, _ref;

BSTree = require('./BSTree');

tree = new BSTree();

_ref = [42, 20, 10, 30, 40, 25, 50, 60, 100, 55, 53, 52];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  value = _ref[_i];
  tree.add(value);
}

console.log(tree.height());
