// Generated by CoffeeScript 1.6.3
var assert, native_array_merge_sort, native_array_quick_sort, should;

assert = require('assert');

should = require('should');

native_array_quick_sort = require('./../../srcs/sorts/native_array_quicksort');

native_array_merge_sort = require('./../../srcs/sorts/native_array_mergesort');

describe("Sorts", function() {
  var sorted_array, to_sort;
  to_sort = [2, 21, 412, 4123, 21, 123412, 9213, 890, 42, 1230, 44433];
  sorted_array = to_sort.sort(function(a, b) {
    return a - b;
  });
  beforeEach(function() {
    return to_sort = [2, 21, 412, 4123, 21, 123412, 9213, 890, 42, 1230, 44433];
  });
  describe("quickSort", function() {
    it("#native_array_quick_sort() should sort an array successfully", function() {
      return native_array_quick_sort(to_sort).should.be.eql(sorted_array);
    });
    return it("#native_array_quick_sort() should sort an array with one element", function() {
      return native_array_quick_sort([1]).should.be.eql([1]);
    });
  });
  return describe("mergeSort", function() {
    return it("#mergeSort() should should sort an array successfully", function() {
      return native_array_merge_sort(to_sort).should.be.eql(sorted_array);
    });
  });
});
