// Generated by CoffeeScript 1.6.3
var BSTree, assert, buckets, t;

assert = require('assert');

BSTree = require('../srcs/BSTree');

buckets = require('./buckets');

t = new buckets.BSTree;

describe('BSTree', function() {
  var bucket_tree, tree;
  tree = new BSTree;
  bucket_tree = new buckets.BSTree;
  beforeEach(function() {});
  return it('#isEmpty() should return true if empty', function() {
    assert(tree.isEmpty);
    return assert.strictEqual(tree.isEmpty(), bucket_tree.isEmpty());
  });
});
