// Generated by CoffeeScript 1.6.3
var native_array_insertion_sort;

native_array_insertion_sort = function(arr) {
  var i, j, tmp;
  i = 0;
  while (i < arr.length) {
    j = i;
    while (j > 0 && arr[j - 1] > arr[j]) {
      tmp = arr[j - 1];
      arr[j - 1] = arr[j];
      arr[j] = tmp;
      j--;
    }
    i++;
  }
  return arr;
};

module.exports = native_array_insertion_sort;
